### ISSUE TITLE
Consider A-Frame

### ISSUE THREAD

**Issue by KJStrand** [w3reality/three-geo#1]
Hi, have you considered creating an [A-Frame](https://aframe.io/docs/0.8.0/introduction/) component for your geographic visualization library? This would allow for mixing the visualizations with other developed components and make VR access automatic. In the example below, I created a simple version of what such a component could look like for three-geo, and placed it in a scene with an environment component and VR hand control components.

Sample:
https://jet-wasp.glitch.me/

Source Code:
https://glitch.com/edit/#!/jet-wasp?path=index.html:71:27

**Comment by j-devel** [comment]
Great!  It's really nice to see three-geo working fine with A-Frame.  Thanks for the informative demo.  We've added it in the use case section:
https://github.com/w3reality/three-geo#who-is-using-three-geo

**Comment by akbartus** [comment]
Hi there! Created the updated version of the component, which is compatible with latest version of A-Frame and has a few more additional features. It was created based on KJStrand's work.
