### ISSUE TITLE
/v4/mapbox.streets-satellite returns 410 gone

### ISSUE THREAD

**Issue by samipe** [w3reality/three-geo#20]
Replacing `streets-satellite` with `satellite` seemed to resolve the issue as there is no map named `streets-satellite` at least in my MapBox dashboard view.

**Comment by j-devel** [comment]
Thanks for the report!  Will release a new version including the fix: https://github.com/w3reality/three-geo/commit/13b47fbcbf15fea043d6b8dceaeeccee2ef984a2
