### ISSUE TITLE
Deprecated parameters

### ISSUE THREAD

**Issue by eserrose** [w3reality/three-geo#21]
Hello,

As of Jun 1, 2020, Mapbox stopped supporting classic styles. ([link](https://docs.mapbox.com/help/troubleshooting/migrate-legacy-static-images-api/?/=blog&utm_source=mapbox-blog&utm_campaign=blog%7Cmapbox-blog%7Cdoc-migrate%7Cdeprecating-studio-classic-styles-d8892ac38cb4-20-03&utm_term=doc-migrate&utm_content=deprecating-studio-classic-styles-d8892ac38cb4)). 

Can you please update the source code? I tired to do it myself, but looks like some styles are created by you, and the new version needs username.

**Comment by j-devel** [comment]
Thanks @eserrose for reporting this! - updated it accordingly.
