### ISSUE TITLE
How to get the mouse click model?

### ISSUE THREAD

**Issue by fengtianxi001** [w3reality/three-geo#27]
I've tried this, but it doesn't work.

    const { offsetX, offsetY } = event; 
    const x = (offsetX / window.innerWidth) * 2 - 1;
    const y = - (offsetY / window.innerHeight) * 2 + 1;
    const mousePoint = new THREE.Vector2(x,y);
    let raycaster = new THREE.Raycaster();
    raycaster.setFromCamera(mousePoint, camera);
    var intersects = raycaster.intersectObjects(scene.children ,true);
    for (var i = 0; i < intersects.length; i++) {
         intersects[i].object.material.color.set(0xff0000);
     }

Looking forward to your reply

**Comment by j-devel** [comment]
For mouse picking 3D objects generated by three-geo, we have at least [one such case](https://github.com/w3reality/three-geo/issues/22#issuecomment-655554370).  It might be helpful for you to study it.
