### ISSUE TITLE
How to reference in Vue

### ISSUE THREAD

**Issue by fengtianxi001** [w3reality/three-geo#29]
I use it this way in Vue component,but it throws an error：THREE is not defined

import * as THREE from "three";
import ThreeGeo from 'three-geo/dist/three-geo.esm.js';

**Comment by j-devel** [comment]
'three-geo.esm.js' expects `THREE` as an external symbol (`window.THREE`). So I guess [using the UMD version of three.js](https://discourse.threejs.org/t/referenceerror-three-is-not-defined/8580/2) would help.

For example: https://github.com/w3reality/three-geo/blob/master/examples/load-esm/index.html

**Comment by j-devel** [comment]
Or, if you want to preserve these lines

```
import * as THREE from 'three';
import ThreeGeo from 'three-geo/dist/three-geo.esm.js';
```

as is, you could do so by adding `import * as THREE from 'three';` in the first line of 'three-geo.esm.js'.

**Comment by fengtianxi001** [comment]
Do it your way and it works. Thank you very much for your answer！！！！
