### ISSUE TITLE
how to get the flat satellite image 

### ISSUE THREAD

**Issue by yash-react-ror-developer** [w3reality/three-geo#4]
This library is providing me the terrain view i need the flat satellite image is it possible here

**Comment by j-devel** [comment]
You can obtain the underlying satellite image data being used for the terrain texture as follows:
```js
        onSatelliteMat: (mesh) => {
            console.log('image:', mesh.material.map.image);

            // ...
        },
```
```
image:
{data: Uint8Array(1048576), width: 512, height: 512}
```

**Comment by yash-react-ror-developer** [comment]
Thank you but both the terrain texture and satellite texture view are different and how is it possible to set the mountain terrain that is above to see level on the origin i am not getting it on the origin 
onSatelliteMat: (plane) => {
            plane.material.side = THREE.DoubleSide
            const planegeo = new THREE.PlaneBufferGeometry(1,1,20,20)
            const material = new THREE.MeshBasicMaterial({side: THREE.DoubleSide, map: plane.material.map})
            const mesh = new THREE.Mesh(planegeo, material)
            mesh.rotation.x = - Math.PI/2
            mesh.name = 'flat-image'
            flatSite.add(mesh)
            
        },

**Comment by yash-react-ror-developer** [comment]
@j-devel is it possible

**Comment by j-devel** [comment]
To render the flatten terrain view, the easiest approach would be just setting `z` values of the terrain's geometry after satellite textures are available:
```js
            onRgbDem: (meshes) => {},
            onSatelliteMat: (mesh) => {
                const position = mesh.geometry.attributes.position;
                const arr = position.array;
                for (let i = 0; i < arr.length; i += 3) {
                    arr[i+2] = 0; // set z value (height) to zero
                }
                position.needsUpdate = true;

                //...
            },
```
See [Example](https://w3reality.github.io/three-geo/examples/flat/index.html) and this ref: https://github.com/w3reality/three-geo/issues/3#issuecomment-442342038
![flatten-terrain-demo](https://user-images.githubusercontent.com/38098238/62995848-953ccf00-be8c-11e9-95c0-452802f75916.png)

**Comment by yash-react-ror-developer** [comment]
its a great help thank you
