### ISSUE TITLE
error with es-pack-js when executing 'npm i'

### ISSUE THREAD

**Issue by letsgo0** [w3reality/three-geo#44]
Hope someone know this problem.  I just clone this repo, cd three-geo and npm i, then comes this error below.  
> node ./postinstall.js

Thank you for installing EJS: built with the Jake JavaScript build tool (https://jakejs.com/)

> es-pack-js@0.5.2 postinstall D:\gisdemo8threejs\three-geo\node_modules\es-pack-js
> (cd ./node-polyfill && npm run install); (cd ./rustwasm-polyfill && npm i);

此时不应有 (cd。
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules\es-pack-js\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! es-pack-js@0.5.2 postinstall: `(cd ./node-polyfill && npm run install); (cd ./rustwasm-polyfill && npm i);`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the es-pack-js@0.5.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

**Comment by canglangshushu** [comment]
Have you solved the problem yet？I ran into the same problem

**Comment by Bextia** [comment]
Same here, can't get the example running locally

**Comment by j-devel** [comment]
To my knowledge, this error happens when building on Windows.

Using the latest es-pack-js (v0.5.3 with [partial Windows support](https://github.com/w3reality/es-pack-js#windows)) might help:
```
$ npm config set script-shell bash
$ npm i es-pack-js@0.5.3
$ npm run build
```

**Comment by Bextia** [comment]
yes, I'm working on Windows.

I've tried your proposed solution and got this error on the second command:

![image](https://user-images.githubusercontent.com/10054456/142190095-4552788c-086e-48b8-934d-1a7c22d6c49b.png)

**Comment by sonicviz** [comment]
Hello.

Windows user here, same error. 

npm run build

> three-geo@1.4.6-dev3 build
> es-pack build -m umd

/bin/bash: es-pack: command not found

Any clues?

**Comment by j-devel** [comment]
> /bin/bash: es-pack: command not found

Try `npm i` first?

**Comment by sonicviz** [comment]
Yes, already did fails. 
Tried npm i es-pack-js@0.5.3 and fails. 

Switching to WSL.

**Comment by sonicviz** [comment]
I switched to WSL2, installed nvm, node etc according to https://learn.microsoft.com/en-us/windows/dev-environment/javascript/nodejs-on-wsl 

All checks out, everything installed. Opened Geo in VScode in WSL via code .

Try npm i or npm i three-geo but it fails now on: npm ERR! /bin/bash: node: command not found

But node is installed. 

node --version
v18.12.1

**Comment by j-devel** [comment]
> I switched to WSL2, installed nvm, node etc according to https://learn.microsoft.com/en-us/windows/dev-environment/javascript/nodejs-on-wsl
> 
> All checks out, everything installed. Opened Geo in VScode in WSL via code .
> 
> Try npm i or npm i three-geo but it fails now on: npm ERR! /bin/bash: node: command not found
> 
> But node is installed.
> 
> node --version v18.12.1

Sorry, I am not familiar with the Windows environment...

FYI - latest CI build on Windows (via GitHub Action's Docker) https://github.com/w3reality/three-geo/actions/runs/4459639864/jobs/7832217785

**Comment by sonicviz** [comment]
Apologies. my mistake. I had skipped a step and VScode wasn't fully hooking into WSL when I booted the project. 

Fixed it, and it's all working fine under WSL2 as per your original docs (after installing node etc as per MS instructions above).

Thanks for the help, sounding board helps troubleshoot. Sorry to bother you, but at least you can add some extra instructions perhaps for WIndows users now to use WSL. Microsoft actually recommends this for js development now anyway, so all good.

**Comment by j-devel** [comment]
@sonicviz  I have [added some notes](https://github.com/w3reality/three-geo#building-on-windows) regarding this.

Thanks for your interest, and looking forward to seeing enhancements!

**Comment by sonicviz** [comment]
No problem.

Q: How do you calculate terrain height relative to the position units in three.js, which are also dependant on the zoom factor?

For example, if I want to position an object 1m above sea level (which according to https://docs.mapbox.com/data/tilesets/guides/access-elevation-data/#mapbox-terrain-rgb sea level is 0) how do I translate that into a relative mesh position,z value that will translate it a unit of 1m (or 10m or whatever) relative to the scale of the mesh terrain elevation? 

Also. how does that position calculation change based on the zoom factor, which can be from 11 to 17?

**Comment by j-devel** [comment]
> Q: How do you calculate terrain height relative to

Okay, I think this is a different issue topic.  Could you open a new thread?

**Comment by sonicviz** [comment]
aok, done. ty
