### ISSUE TITLE
none of the live demo's work

### ISSUE THREAD

**Issue by PerspectivesLab** [w3reality/three-geo#51]
all examples have error :
Uncaught (in promise) TypeError: Super expression must either be null or a function
    at app.esm.dev.js:2:341338
    at app.esm.dev.js:2:341510
    at Object.7240 (app.esm.dev.js:2:343246)
    at n (app.esm.dev.js:2:480766)
    at app.esm.dev.js:2:481372
    at app.esm.dev.js:2:481381

**Comment by j-devel** [comment]
It looks like you are testing geo-viewer?  I cannot reproduce the error.

Did you exactly follow the instructions? https://github.com/w3reality/three-geo/tree/master/examples/geo-viewer#build

**Comment by PerspectivesLab** [comment]
@j-devel i am testing the page https://github.com/w3reality/three-geo
and the 'live' links for testing: none of the links work,
thank you

**Comment by PerspectivesLab** [comment]
keep up the great work @j-devel thx
